version: '3'
services:
  frontend: 
    build: .
    container_name: 'frontend'
    ports: 
      - '3000:3000'
    volumes:
      - .:/app
    working_dir: /app
    #command: bash -c "cd app && npm run dev"
    stdin_open: true
    tty: true
